"""initial schema: feeds and entries

Revision ID: 0001
Revises:
Create Date: 2026-04-10

Creates the core data model defined in ADR 001, docs/spec/feed.md, and
docs/spec/entry.md. Includes all columns (API-exposed lifecycle fields
AND internal scheduler metadata), unique constraint on (feed_id, guid),
retention-sweep index on entries.fetched_at, and the compound keyset
index (feed_id, published_at DESC, id DESC) for GET /v1/entries.

Hand-written rather than autogenerated so it works without a live DB at
generation time.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "feeds",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("effective_url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.String(length=32),
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "last_successful_fetch_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "last_attempt_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "next_fetch_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("etag", sa.Text(), nullable=True),
        sa.Column("last_modified", sa.Text(), nullable=True),
        sa.Column(
            "consecutive_failures",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_index("ix_feeds_status", "feeds", ["status"])
    op.create_index(
        "ix_feeds_next_fetch_at_active",
        "feeds",
        ["next_fetch_at"],
        postgresql_where=sa.text("status = 'active'"),
    )

    op.create_table(
        "entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("feed_id", sa.Integer(), nullable=False),
        sa.Column("guid", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("author", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "content_updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["feed_id"],
            ["feeds.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("feed_id", "guid", name="uq_entries_feed_guid"),
    )
    op.create_index("ix_entries_fetched_at", "entries", ["fetched_at"])
    # Compound keyset index with DESC ordering for (published_at, id).
    op.create_index(
        "ix_entries_feed_pub_id",
        "entries",
        [
            sa.text("feed_id"),
            sa.text("published_at DESC"),
            sa.text("id DESC"),
        ],
    )


def downgrade() -> None:
    op.drop_index("ix_entries_feed_pub_id", table_name="entries")
    op.drop_index("ix_entries_fetched_at", table_name="entries")
    op.drop_table("entries")
    op.drop_index("ix_feeds_next_fetch_at_active", table_name="feeds")
    op.drop_index("ix_feeds_status", table_name="feeds")
    op.drop_table("feeds")
